- name: Check If Swap File Exists
  stat:
    path: "/swapfile"
  register: swap_file_check

- name: Create Swap File
  command: fallocate -l 1G /swapfile
  when: not swap_file_check.stat.exists


- name: Set Permissions On Swap File
  file:
    path: "/swapfile"
    mode: 0600
  when: not swap_file_check.stat.exists

- name: format swap file
  command: mkswap /swapfile
  when: not swap_file_check.stat.exists

- name: add to fstab
  lineinfile:
    dest: /etc/fstab
    regexp: "swapfile"
    line: "/swapfile none swap sw 0 0"
  when: not swap_file_check.stat.exists
  
- name: turn on swap
  command: swapon -a
  when: not swap_file_check.stat.exists

- name: set swapiness
  sysctl:
    name: vm.swappiness
    value: "1"
  when: not swap_file_check.stat.exists